version: '3'
services:
  db:
    build:
      context: .
      dockerfile: docker/Dockerfile.db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: furry_fotky
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d furry_fotky"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      db:
        condition: service_healthy

volumes:
  pg_data: 